apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  volumes:
  - name: app
    emptyDir: {}
  initContainers:
  - name: generate-intex
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - mountPath: /app
      name: app
  containers:
  - name: web
    image: ssi91/otus-nginx:0.1
    volumeMounts:
    - mountPath: /app
      name: app
    ports:
      - containerPort: 8000
